name: CI
on:
    push:
        branches: master
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Branch name
              run: echo running on branch ${GITHUB_REF##*/}
            - name: github.ref name
              run: echo $github.ref
    staging:
        if: contains(github.ref, 'test')
        name: Staging
        runs-on: ubuntu-latest

        steps:
            - name: Enter step
              run: echo Enter step
