name: CI
on:
    pull_request:
    
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Branch name
              run: echo running on branch ${{github.ref}}
            - name: target PR name
              run: echo running on branch ${{github.base_ref}}
            - name: source PR name
              run: echo running on branch ${{github.head_ref}}
    staging:
        if: contains(github.head_ref, 'test')
        name: Staging
        runs-on: ubuntu-latest

        steps:
            - name: Enter step
              run: echo Enter step
